---
# Install jira

- name: create system user
  user:
    name={{ jira_user }}
    password={{ jira_pass }}
    home={{ jira_home }}
    system=yes
    shell=/bin/bash

- name: preapre directories
  file:
    path={{ item }}
    owner={{ jira_user }}
    group={{ jira_user }}
    state=directory
  with_items:
    - "{{ jira_config }}"
    - "{{ jira_catalina }}"

- name: copy init.d script
  template:
    src=jira.j2
    dest=/etc/init.d/jira
    owner={{ jira_user }}
    group={{ jira_user }}
    mode=0755

- name: copy setenv.sh
  template:
    src="{{ item }}.j2"
    dest="/etc/jira/{{ item }}"
    owner={{ jira_user }}
    group={{ jira_user }}
    mode=0644
  with_items:
    - setenv.sh
    - server.xml
    - dbconfig.xml
