---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- include: install_crowd.yml
- include: install_jira.yml
- include: install_confluence.yml
- include: install_bitbucket.yml
- include: install_bamboo.yml
