---
# The variables file used by the playbooks in the bitbucket_servers group.

bitbucket_archive: /tmp/bitbucket.tar.gz
bitbucket_catalina: /usr/share/bitbucket
bitbucket_config: /etc/bitbucket
bitbucket_home: /var/lib/bitbucket
bitbucket_pass: Xieh7xah
bitbucket_sha256: 458addf0648186c90f7ffb026eb9464182e03c44a03c5658fe0cb44d2495df09
bitbucket_url: https://downloads.atlassian.com/software/stash/downloads/atlassian-bitbucket-4.0.3.tar.gz
bitbucket_user: bitbucket
