---
# Install confluence

- name: create system user
  user:
    name={{ confluence_user }}
    password={{ confluence_pass }}
    home={{ confluence_home }}
    system=yes
    shell=/bin/bash

- name: preapre directories
  file:
    path={{ item }}
    owner={{ confluence_user }}
    group={{ confluence_user }}
    state=directory
  with_items:
    - "{{ confluence_config }}"
    - "{{ confluence_catalina }}"

- name: copy init.d script
  template:
    src=confluence.j2
    dest=/etc/init.d/confluence
    owner={{ confluence_user }}
    group={{ confluence_user }}
    mode=0755

- name: copy config files
  template:
    src="{{ item }}.j2"
    dest="/etc/confluence/{{ item }}"
    owner={{ confluence_user }}
    group={{ confluence_user }}
    mode=0644
  with_items:
    - setenv.sh
    - server.xml

- name: download package
  get_url:
    url={{ confluence_url }}
    dest={{ confluence_archive }}
    sha256sum={{ confluence_sha256 }}

- name: unarchive package
  shell: tar zxvf {{ confluence_archive }} -C {{ confluence_catalina }} --strip-components=1; chown -Rf {{ confluence_user }}:{{ confluence_user }} {{ confluence_catalina }}
  args:
    creates: "{{ confluence_catalina }}/bin/start-confluence.sh"

- name: relink setenv.sh
  file:
    src="{{ confluence_config }}/setenv.sh"
    dest="{{ confluence_catalina }}/bin/setenv.sh"
    state=link
    force=yes

- name: relink server.xml
  file:
    src="{{ confluence_config }}/server.xml"
    dest="{{ confluence_catalina }}/conf/server.xml"
    state=link
    force=yes

- name: create postgresql user
  become: yes
  become_user: postgres
  postgresql_user: name={{ confluence_user }} password={{ confluence_pass }}

- name: create postgresql db
  become: yes
  become_user: postgres
  postgresql_db: name={{ confluence_user }} owner={{ confluence_user }} encoding=UNICODE lc_collate=C lc_ctype=C template=template0

- name: enable service
  service: name=confluence enabled=yes
  notify: restart confluence
